### Create User
POST http://localhost:3000/auth/create
Content-Type: application/json

{
    "username": "lunden-graph",
    "password": "seba2010"
}


### Login USER
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "username": "lunden-graph",
    "password": "seba2010"
}

### TOKEN (created At 03/03/25): eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJsdW5kZW4tZ3JhcGgiLCJpYXQiOjE3NDEwNTEwNzksImV4cCI6MTc0MTY1NTg3OX0.VdbVvXHrAHCOvBSNta4JYCHYRZq5Kg0xBPnnxf-ZidE



### Testing Token
POST http://localhost:3000/auth/token
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJsdW5kZW4tZ3JhcGgiLCJpYXQiOjE3NDEwNTEwNzksImV4cCI6MTc0MTY1NTg3OX0.VdbVvXHrAHCOvBSNta4JYCHYRZq5Kg0xBPnnxf-ZidE




### Testing Token show
POST http://localhost:3000/test/asd
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJsdW5kZW4tZ3JhcGgiLCJpYXQiOjE3NDEwNTEwNzksImV4cCI6MTc0MTY1NTg3OX0.VdbVvXHrAHCOvBSNta4JYCHYRZq5Kg0xBPnnxf-ZidE



### Saving Record DATUM
POST http://localhost:3000/datum/save
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJsdW5kZW4tZ3JhcGgiLCJpYXQiOjE3NDEwNTEwNzksImV4cCI6MTc0MTY1NTg3OX0.VdbVvXHrAHCOvBSNta4JYCHYRZq5Kg0xBPnnxf-ZidE

{
    "emailSource": "adalirmaroll@yahoo.com",
    "emailSourcePsw":"SeBa2010",
    "xUser": "@Adalir_noob",
    "xPsw": "SeBa2010"
}


### Saving Record API DATA
POST http://localhost:3000/apidata/save
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJsdW5kZW4tZ3JhcGgiLCJpYXQiOjE3NDEwNTEwNzksImV4cCI6MTc0MTY1NTg3OX0.VdbVvXHrAHCOvBSNta4JYCHYRZq5Kg0xBPnnxf-ZidE

{
    "appName": "Adalir_noob",
    "appId":"30262849",
    "dataId": 1,
}