### Create User
POST http://localhost:3000/user/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJmNjdjYWNhLTVkZDgtNGNhMS04ZDNkLWEyNTE1YzM2NDg2YSIsInVzZXJuYW1lIjoiZ29kbGVzcy1hdGxhcyIsImN1cnJlbnREYXRlIjoiVHVlIE1hciAyNSAyMDI1IDE4OjUzOjQxIEdNVC0wMzAwIChob3JhIGVzdMOhbmRhciBkZSBBcmdlbnRpbmEpIiwiaXNTdXBlckFkbWluIjp0cnVlLCJpYXQiOjE3NDI5Mzk2MjEsImV4cCI6MTc0MzU0NDQyMX0.Q1Fl-Zhijv_xz2_DqXv2fVWFaHpqPwP3zMHcilE0Lgw

{
    "username": "finde",
    "password": "seba",
    "isSuperAdmin": true
}



### Login User
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "username": "finder-cloud",
    "password": "seba2010"
}




### Adding Datum
POST http://localhost:3000/datum/save
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk3ZjA1MTM4LTg4MmQtNDdlOC1iNWQxLTVkZThhZjA0NjcxNCIsInVzZXJuYW1lIjoiZmluZGVyLWNsb3VkIiwiY3VycmVudERhdGUiOiJUdWUgQXByIDA4IDIwMjUgMTk6MjQ6MzYgR01ULTAzMDAgKGhvcmEgZXN0w6FuZGFyIGRlIEFyZ2VudGluYSkiLCJpc1N1cGVyQWRtaW4iOnRydWUsImlhdCI6MTc0NDE1MTA3NiwiZXhwIjoxNzQ0MTUxMDg2fQ.DxUzdvK7qPCmiWwG748JaP79Y_5vxPwmn8wcbVQCIVY
Set-:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk3ZjA1MTM4LTg4MmQtNDdlOC1iNWQxLTVkZThhZjA0NjcxNCIsInVzZXJuYW1lIjoiZmluZGVyLWNsb3VkIiwiY3VycmVudERhdGUiOiJUdWUgQXByIDA4IDIwMjUgMTk6MjQ6MzYgR01ULTAzMDAgKGhvcmEgZXN0w6FuZGFyIGRlIEFyZ2VudGluYSkiLCJpc1N1cGVyQWRtaW4iOnRydWUsImlhdCI6MTc0NDE1MTA3NiwiZXhwIjoxNzQ0MjM3NDc2fQ.HheCzg_QlOBnWkYHTpy9YVQvEcDt_tdoVzZVtuZJo4M

{
    "emailSource": "landad@mailer.com",
    "emailSourcePsw" : "seba2010",
    "xUser": "calloric",
    "xPsw": "seba2010"
}