### Create User
POST http://localhost:3000/auth/create
Content-Type: application/json

{
    "username": "asperion-gasp",
    "password": "seba2010",
    "role": "super-admin"
}


### Login USER
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "username": "lunden-graph",
    "password": "seba2010"
}


### TOKEN --NOT VALID-- (created At 09/03/25): eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJjYzAzZTZlLWQyMGUtNGY2MC04YzMxLWJkZmJiYTU1ZGM5MyIsInVzZXJuYW1lIjoibHVuZGVuLWdyYXBoIiwiY3VycmVudERhdGUiOiJTdW4gTWFyIDA5IDIwMjUgMTg6NDM6MDQgR01ULTAzMDAgKGhvcmEgZXN0w6FuZGFyIGRlIEFyZ2VudGluYSkiLCJpYXQiOjE3NDE1NTY1ODUsImV4cCI6MTc0MjE2MTM4NX0.9imtGe5zW2_DSnnLkgqIPGf1HJByKQPY66oUORG2bes


### Testing Token
POST http://localhost:3000/auth/token
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJjYzAzZTZlLWQyMGUtNGY2MC04YzMxLWJkZmJiYTU1ZGM5MyIsInVzZXJuYW1lIjoibHVuZGVuLWdyYXBoIiwiY3VycmVudERhdGUiOiJTdW4gTWFyIDA5IDIwMjUgMTg6NDM6MDQgR01ULTAzMDAgKGhvcmEgZXN0w6FuZGFyIGRlIEFyZ2VudGluYSkiLCJpYXQiOjE3NDE1NTY1ODUsImV4cCI6MTc0MjE2MTM4NX0.9imtGe5zW2_DSnnLkgqIPGf1HJByKQPY66oUORG2bes




### Testing Token show
POST http://localhost:3000/test/asd
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJsdW5kZW4tZ3JhcGgiLCJpYXQiOjE3NDEwNTEwNzksImV4cCI6MTc0MTY1NTg3OX0.VdbVvXHrAHCOvBSNta4JYCHYRZq5Kg0xBPnnxf-ZidE



### Saving Record DATUM
POST http://localhost:3000/datum/save
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJsdW5kZW4tZ3JhcGgiLCJpYXQiOjE3NDEwNTEwNzksImV4cCI6MTc0MTY1NTg3OX0.VdbVvXHrAHCOvBSNta4JYCHYRZq5Kg0xBPnnxf-ZidE

{
    "emailSource": "vendorrough1@gmail.com",
    "emailSourcePsw":"SeBa2010",
    "xUser": "@aftertos",
    "xPsw": "SeBa2010"
}



### Saving Record API DATA
POST http://localhost:3000/apidata/save
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJsdW5kZW4tZ3JhcGgiLCJpYXQiOjE3NDEwNTEwNzksImV4cCI6MTc0MTY1NTg3OX0.VdbVvXHrAHCOvBSNta4JYCHYRZq5Kg0xBPnnxf-ZidE

{
    "appName": "aftertos_noun",
    "appId":"30262026",
    "dataId": 2
}



### Saving Record API KEY
POST http://localhost:3000/apikey/save
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJsdW5kZW4tZ3JhcGgiLCJpYXQiOjE3NDEwNTEwNzksImV4cCI6MTc0MTY1NTg3OX0.VdbVvXHrAHCOvBSNta4JYCHYRZq5Kg0xBPnnxf-ZidE

{
    "apiKey": "X5Ls7QG5OKByB8xwFDZSXlVzz",
    "apiKeySecret":"DXbntusIqUBBiB9miRu7VfeZoIlm8ByocPEOpiUZfw1LvXp10G",
    "bearerToken": "AAAAAAAAAAAAAAAAAAAAAArDzQEAAAAAXGR4%2FsfKImfTao8W76iZqCgnLOg%3DUxdYO51gzLi8wXHTw2QCuHKDraoXCGTbTWJsBPufTSdXjtGFIu",
    "accessToken": "1892697858815524864-J7knXkGaaWnYwJj69OccWAMW1RWASd",
    "accessTokenSecret": "TH2yBlFBdLLGqq4PJjtFnWKShwl6PgI5hA36sQf828ltX",
    "apiDataId": 2,
    "dataId": 2
}



### Select Single Record
POST http://localhost:3000/datum/select-single
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJsdW5kZW4tZ3JhcGgiLCJpYXQiOjE3NDEwNTEwNzksImV4cCI6MTc0MTY1NTg3OX0.VdbVvXHrAHCOvBSNta4JYCHYRZq5Kg0xBPnnxf-ZidE

{
    "emailSource": "adalirmaroll@yahoo.com"
}


### Select ALL
GET http://localhost:3000/datum/select-all
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJsdW5kZW4tZ3JhcGgiLCJpYXQiOjE3NDEwNTEwNzksImV4cCI6MTc0MTY1NTg3OX0.VdbVvXHrAHCOvBSNta4JYCHYRZq5Kg0xBPnnxf-ZidE



### Testing protected route
POST http://localhost:3000/test/bop
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJjYzAzZTZlLWQyMGUtNGY2MC04YzMxLWJkZmJiYTU1ZGM5MyIsInVzZXJuYW1lIjoibHVuZGVuLWdyYXBoIiwiY3VycmVudERhdGUiOiJTdW4gTWFyIDA5IDIwMjUgMTg6NDM6MDQgR01ULTAzMDAgKGhvcmEgZXN0w6FuZGFyIGRlIEFyZ2VudGluYSkiLCJpYXQiOjE3NDE1NTY1ODUsImV4cCI6MTc0MjE2MTM4NX0.9imtGe5zW2_DSnnLkgqIPGf1HJByKQPY66oUORG2bes

{
    "role" : false
}