export const PRISMA_ERROR_CODES = {
    P2000: {description:"The provided value for the column is too long for the column's type. Column: {column_name}" , status_code:400},
    P2001: {description:"The record searched for in the where condition ({model_name}.{argument_name} = {argument_value}) does not exist", status_code:404},
    P2002: {description:"Unique constraint failed on the {constraint}", status_code:409},
    P2003: {description:"Foreign key constraint failed on the field: {field_name}", status_code:409},
    P2004: {description:"A constraint failed on the database: {database_error}", code:400},
    P2005: {description:"The value {field_value} stored in the database for the field {field_name} is invalid for the field's type", status_code:400},
    P2006: {description:"The provided value {field_value} for {model_name} field {field_name} is not valid", status_code:400},
    P2007: {description:"Data validation error {database_error}", status_code:400},
    P2008: {description:"Failed to parse the query {query_parsing_error} at {query_position}", status_code:400},
    P2009: {description:"Failed to validate the query: {query_validation_error} at {query_position}", status_code:400},
    P2010: {description:"Raw query failed. Code: {code}. Message: {message}", status_code:500},
    P2011: {description: "Null constraint violation on the {constraint}", status_code:400},
    P2012: {description:"Missing a required value at {path}", status_code:400},
    P2013: {description:"Missing the required argument {argument_name} for field {field_name} on {object_name}.", status_code:400},
    P2014: {description:"The change you are trying to make would violate the required relation '{relation_name}' between the {model_a_name} and {model_b_name} models.", status_code:400},
    P2015: {description:"A related record could not be found. {details}", status_code:404},
    P2016: {description:"Query interpretation error. {details}", status_code:400},
    P2017: {description:"The records for relation {relation_name} between the {parent_name} and {child_name} models are not connected.", status_code:400},
    P2018: {description:"The required connected records were not found. {details}", status_code:404},
    P2019: {description:"Input error. {details}", status_code: 400},
    P2020: {description:"Value out of range for the type. {details}", status_code:400},
    P2021: {description:"The table {table} does not exist in the current database.", status_code:404},
    P2022: {description:"The column {column} does not exist in the current database.", status_code:404},
    P2023: {description:"Inconsistent column data: {message}",status_code:400},
    P2024: {description:"Timed out fetching a new connection from the connection pool. (More info: http://pris.ly/d/connection-pool (Current connection pool timeout: {timeout}, connection limit: {connection_limit})", status_code:500},
    P2025: {description:"An operation failed because it depends on one or more records that were required but not found. {cause}", status_code:404},
    P2026: {description:"The current database provider doesn't support a feature that the query used: {feature}", status_code:400},
    P2027: {description:"Multiple errors occurred on the database during query execution: {errors}", status_code:500}
}