name: Api & Account to Social Network Bot
# See more on: https://medium.com/@cdndns/how-to-use-github-action-cicd-for-nodejs-78333c4296fa
# See this too: https://medium.com/@offbeatgs/github-action-for-lint-127f28fbc739
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
          matrix:
            node-version: [18]

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.node-version }}
             
            - name: Install dependencies
              run: npm install
            
            - name: Run Lint
              run: npm run eslint
            - name: Build Project
              run: npm run build
            
            - name: Upload build artifacts
              if: success()
              uses: actions/upload-artifact@v4
              with:
                name: build
                path: ./build